language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: CueHEMAvgSA6sBaqkw2/NZIbmGmL3ERPOLR+9RdFQpBecjey4R1xlLy+oi+eNqs6ds4LvsC00jyOTlJKRDGhABdi0+4eWeAgTbMfGZSoKzpWLYtGt5Sj12A0tNFlxHQ0264Tc5XbkWfaO/yGvxF0Vg6kRoe5V4TRU8rGSfTU5bq+wTckIeqYu0n8v8AnawqKPrNO3PTXjPC3WzQR3nN3+m7wL0jX+8tDmPkyc5d3oUI3nA0q/QRWG4FByF3KppPyjecfNoVRnd1srAgc3LQXQXVovr4S7/gH9iJN26/GCxoOWlN4F5n0cg0WaehV3s7hYzZnAFNPF5U88o1LujAGKXvpnj/u9m41IcO6S4sy1qrRHhE9T2JeXVNfZvZhtFz9aTaXwUyvrNfsAzln154iwcOix4WyaIASrlYAu50DCDNo16gInXZ7mGu+zErl6zB4JZ6IMTUG0LSMEI/MWyiOXJgDkl8UW68jFYoB69NR8UR9SMIxjRvrMqCslrg8TjSfX8hIn2oWZhLDe+FeAsVDRaetKveUZA0Uk8w++j/VD6zpfPfHmeuJIoaEdTKe1Vs9pIkxejOt8JTcqIT1fcoqwOfvMvEVYyXa7Nqxuq5lVFK6iDvpePteWaFDK65J6l/M7WSBlRP6UuWdWa2qw9fno6VOdjwGYFxTqkztrhNu1wA=
  cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: xinp-hub/pydiggs
    python: 3.8
env:
  global:
    secure: EkO7/LmXi/1c6H1G2XMUhdGzAsbg0Z5jO+R7cwk8ZH691iKhDWPsFIORplI/2M/4sXG9CzX3GIxfMz5XTY42t7Brfj2VN8Q2g6N3tOahLXniBdr+bCbJCsBFFu22KJm7EeP3aLwiaJa5xfcz/MOBA401lLh/ytdMtj2UbhLPVaZkculT48AfcJjof5N55H4+GtKRwZW2mG5uA/LX0V14BspuzAT9x4jcOHckeePpHzCF6ahJHSJBp2IRxuL/fZmfMrmVGVttmjzxVIlPaKB6rHMYmC46sIEIIrYAjnYuifsQeAqu3wnQQVcfB6H/m8ROq7U+DsWT5/6fX7cCU90VzGU3hs4Ry1gMZWFKX/zfnsmVxN6wafCtsG+J8jcBJyNMT56KZUqBDWegpqiGlCc5QKcBqgs6Jarq7e17Hw1neYT3svOjq/sIRe1/LNwDunMIQ8QHtlRPIPH3YP6iiG1Cec5gdMFw/eaRuy04it2UtRDPEulV9+mPfw9HUw4dZte7wgCQxdXcGvjyPhz+sW644PX2i5Jw6OHEroUVvYvZffpUW9u9sFvFM1cbLQ6og+g7u17SCJO1fksC92gIrOgO8CnwvjoByLLoGTVaUn+lMtSVRxH9II52k6kS65MzQeEst4Ll30AP6GPPTrQqTzByX+rGzr9zAaS5hVml8IMHBe8=
