language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: LSJsXod5AwQ9xusR3w9Uw8VMRwKZn1eyeBvKhLLNd+KSSMkUNZ/kADkqKvPEEELG82RMarnLcO3NF0angkguJ3BAockvwUEZ4CQMlO1afFQqsYZylhwYskFsmNYPEmMWJnQtLSPJ+40sgjVAJFu4TmPmTtb+2hnPU08TKWNqwVBnUJgTfo6exT/DMd29NJi0kqFxkWGKFxov5qxhJLQ6SXIBYSaViB61rx4TgMbZBl3ZKnTHgpcYPV59cu/Uq5OOkTUViuDfHm/G0F/K4Oauw1KrixnyfISn8yXXe0eEUda/biMWykqrshPdN0r+ALVVMEsT3Jm7Hpzg1SZKcxhgcKCRG/gX9plLsQaW9Wj2wSuFKY2Ssem68bT6+sJhX7lU2L8N7OgYwLVlS/WqLHxpH75/0m4pNYngyc13VnSJWL8p3Pxr8LCEuxSXuPskDoGZWqF1BWFMus1UWsghI3I5SS3D7d3ueLjgoxOL58Tr3epb+0Hgo9fY3+L2pP5P42XzNqXB2O4TgvNiqKkgX0rx1M3C8fLGgRpQlXheWZXcyGwgDHhmnv8rgHlxQzXfZdZbUj5yfTMfKuJC6F4o8tMRNyLFbjyZOmjxBh5NaOOwiYtwpVPkYLAk3deCBeFE/eiJ92Az2X4HMjBo3BtqjixPDXkHcOnmTN3kKm3BQf2A3sY=
  cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: xinp-hub/pydiggs
    python: 3.8
env:
  global:
    secure: EkO7/LmXi/1c6H1G2XMUhdGzAsbg0Z5jO+R7cwk8ZH691iKhDWPsFIORplI/2M/4sXG9CzX3GIxfMz5XTY42t7Brfj2VN8Q2g6N3tOahLXniBdr+bCbJCsBFFu22KJm7EeP3aLwiaJa5xfcz/MOBA401lLh/ytdMtj2UbhLPVaZkculT48AfcJjof5N55H4+GtKRwZW2mG5uA/LX0V14BspuzAT9x4jcOHckeePpHzCF6ahJHSJBp2IRxuL/fZmfMrmVGVttmjzxVIlPaKB6rHMYmC46sIEIIrYAjnYuifsQeAqu3wnQQVcfB6H/m8ROq7U+DsWT5/6fX7cCU90VzGU3hs4Ry1gMZWFKX/zfnsmVxN6wafCtsG+J8jcBJyNMT56KZUqBDWegpqiGlCc5QKcBqgs6Jarq7e17Hw1neYT3svOjq/sIRe1/LNwDunMIQ8QHtlRPIPH3YP6iiG1Cec5gdMFw/eaRuy04it2UtRDPEulV9+mPfw9HUw4dZte7wgCQxdXcGvjyPhz+sW644PX2i5Jw6OHEroUVvYvZffpUW9u9sFvFM1cbLQ6og+g7u17SCJO1fksC92gIrOgO8CnwvjoByLLoGTVaUn+lMtSVRxH9II52k6kS65MzQeEst4Ll30AP6GPPTrQqTzByX+rGzr9zAaS5hVml8IMHBe8=
