language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Xin.Peng
  password:
    secure: eYZxJFPKrEEX9vdInzuXBCexu+WUk2Pdh3AP9QdW06BlhwGDkwZc1zWjPA38wPelGP2wU7g4ehQDj+6UWB74bcC787NQbmgh+ns9eS4XZD0+QSnSKmGwUS8ggepMIuKpKXLuw1idHhvkamZqfi9Rv4J9WX4wF1SmmX5RPEDylBbiZClNILaywCZJKUSi+VhhuCiB1EfYfzZ9qkT2darbKY8xNoQ9gRR4QwJ5Ib50EJDUZsJrJfjY0b2LrLJoqCYoGbYN/ooKNkXy6BQFJtzkX1jOnPsyh9yo22aN251zujAoT8dops0TCY0K3FFywNZCGNN2X+uGVZFf+qIP3BAaVksxAHB5k0F8BZkZeVz2WZ8Dj0jrbo1O6SbU/90P9S2EzUWLdTdGOLEN04Aq7DLZb2mqU0cApFU0z4SPHpavVBoDKx/sewpxElO+25J5PWWGHpWItx2dTIdAgvxTYWx7yfzviEFjICm+FU2dWmu+EX3JzcyhcaASP76svAb1SJ+j9HbUbbBqs/rbjrKJebIWDZHTB5PcjVoPs8KjqyL7ac+X5Q04jU29XPF/4zX2ihp8l7+/TXr+2MG6z60edQoPls5jsJkwdELGOriGUMofi+WdwdTM2mUNYBaOvj477zHgKPJQO3evmmdTMs5xlBS4Cr+Io18OIAX4btbJKrlMm+Y=
  on:
    tags: true
    repo: xinp_hub/pydiggs
    python: 3.8
env:
  global:
  - secure: EkO7/LmXi/1c6H1G2XMUhdGzAsbg0Z5jO+R7cwk8ZH691iKhDWPsFIORplI/2M/4sXG9CzX3GIxfMz5XTY42t7Brfj2VN8Q2g6N3tOahLXniBdr+bCbJCsBFFu22KJm7EeP3aLwiaJa5xfcz/MOBA401lLh/ytdMtj2UbhLPVaZkculT48AfcJjof5N55H4+GtKRwZW2mG5uA/LX0V14BspuzAT9x4jcOHckeePpHzCF6ahJHSJBp2IRxuL/fZmfMrmVGVttmjzxVIlPaKB6rHMYmC46sIEIIrYAjnYuifsQeAqu3wnQQVcfB6H/m8ROq7U+DsWT5/6fX7cCU90VzGU3hs4Ry1gMZWFKX/zfnsmVxN6wafCtsG+J8jcBJyNMT56KZUqBDWegpqiGlCc5QKcBqgs6Jarq7e17Hw1neYT3svOjq/sIRe1/LNwDunMIQ8QHtlRPIPH3YP6iiG1Cec5gdMFw/eaRuy04it2UtRDPEulV9+mPfw9HUw4dZte7wgCQxdXcGvjyPhz+sW644PX2i5Jw6OHEroUVvYvZffpUW9u9sFvFM1cbLQ6og+g7u17SCJO1fksC92gIrOgO8CnwvjoByLLoGTVaUn+lMtSVRxH9II52k6kS65MzQeEst4Ll30AP6GPPTrQqTzByX+rGzr9zAaS5hVml8IMHBe8=
  - secure: gDa/D54fNt/BNYJ4HTyWrUKikXMZKTluwzK5P7dmtfFTkitR4z2/A7X628yEvGqm5ATOdr0VLhEc4WU4LtlPSrxbUyYFuhyOEaHh7ws0HmNdhSh2ogz2/ufzZskWlQ7g4G8oJAi9upj62S3ERJz8dC5VVN8kIY/iW5pbv0FqOmewEENOT9cCy+Jym3hYGkiqH9RDBCRJvujRewQByLfGWEtfCFokZqZgPZXUhgrriioUB1n6Bn00q0SkQ/OdI7YPRoPRhS6oma6lybCpayWJr9yUEa8bj2/aqNs9jQhtKj9AmxoR+WLo6X4XWGPDogPYdld8gqgAmpSdo78Er4Z3uOhN4yFQX2/cYrLinXkQENDRYPqjCiJ/xMRT3FzmqraXhUTqHIpQDCUaDTSE9fMj3NduzgRG2KdzmGoni7xNygzcrVmc+qHze88pCcOLV8W8HUh1XPZ4mCNupmL6FrsXTHcOLL3LJVqHKRKyhPYgEXqtjiefA7/7gBBKva1X8guJTYUh4Y3ft0KxpgaN8T6dOTg+JvR3zEXb9O/6Cf7f20syVMNupgIoi+QRVq8rzp9Asj9btEhgDu4aKO0sPYuNCFZLGmvdWQg4Y9Vey5bg4JBsTtGLJtVPN9im+Q0MA9ERcSvA4JcgjLcccCMDV4YsHtCQpgvBTtAG1xfyfuqaKWA=
