language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: fARL5kqUTfQfdsDs/9PBPva3v199m6yIce55WN65vkIwsoyBas6r3kWoVtAnBQ5BPBMy9OXRiLOlxibxTKuLF9tDlA8xWasFSNXCA9OttnbL8V2c1CsrDuRObqxH+qTdlAcyerCQwZq/7dpnp3JYJ+dqHKObTDoRu2uGcHzr59Tw0n4jNUCE/yPSK1DfAfK+Sf5feYKF4C8VzJ1LqyGIZWYia5MxumaueplxC9NjuWJ1JD1xKkmJIy1f8qfhFhB4Y96DhuURrdIlJlQZlkqsKNg/T++3mOmHM6kPC9yJJX4bGWrdcPUW2nveT9oUT/pqnZ22mGbElZamdZrtWBgnyEHiTCJ2/KpIsLEVTv2aN8xsSW5+AfIloIfhIaw6rz3b/XqEQOYkUgl3cPoZPIDEwVSn8EkZpdxbcpQizGn4WJhvrZY4QiNaAnkXYVQIBHBdFgieqKdM6KY5ZgCCtqpx2hzbzr/e3FFYaG5f1HgN7raxLHGjQxMNkWIF/qaNJ626M+mnEi8NoFGnOVaWW9SqLO+vHq8gaiiVat521CO+jjvrCTZbbeyYW3KBqkO8VDg+GWn+pLv3YayN9ZZYpv3rzMT0ktXBeA89R+MAQjrw6X3plOlup/FegobwYAeruRTJnQFPAyw33odIEWhYptIJZel8SmZplPw6U2slKe7E+7w=
  cleanup: true
  skip_existing: true
  on:
    repo: xinp-hub/pydiggs
    python: 3.8
env:
  global:
    secure: EkO7/LmXi/1c6H1G2XMUhdGzAsbg0Z5jO+R7cwk8ZH691iKhDWPsFIORplI/2M/4sXG9CzX3GIxfMz5XTY42t7Brfj2VN8Q2g6N3tOahLXniBdr+bCbJCsBFFu22KJm7EeP3aLwiaJa5xfcz/MOBA401lLh/ytdMtj2UbhLPVaZkculT48AfcJjof5N55H4+GtKRwZW2mG5uA/LX0V14BspuzAT9x4jcOHckeePpHzCF6ahJHSJBp2IRxuL/fZmfMrmVGVttmjzxVIlPaKB6rHMYmC46sIEIIrYAjnYuifsQeAqu3wnQQVcfB6H/m8ROq7U+DsWT5/6fX7cCU90VzGU3hs4Ry1gMZWFKX/zfnsmVxN6wafCtsG+J8jcBJyNMT56KZUqBDWegpqiGlCc5QKcBqgs6Jarq7e17Hw1neYT3svOjq/sIRe1/LNwDunMIQ8QHtlRPIPH3YP6iiG1Cec5gdMFw/eaRuy04it2UtRDPEulV9+mPfw9HUw4dZte7wgCQxdXcGvjyPhz+sW644PX2i5Jw6OHEroUVvYvZffpUW9u9sFvFM1cbLQ6og+g7u17SCJO1fksC92gIrOgO8CnwvjoByLLoGTVaUn+lMtSVRxH9II52k6kS65MzQeEst4Ll30AP6GPPTrQqTzByX+rGzr9zAaS5hVml8IMHBe8=
