language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: h+aLm8in8LlPvgaSff+sZv+/vRlSY/kkn/OvR9iwXl6zMFnvWPHqdXMkqAY5st7oYGBSQDsuY/DTwlnu5me5iHGnAKc3HBmNUeVC8xNjWBPEfvzYVXHDkMaKfz1fR/c6RwUDlzG4/gGlVKvnBVX0bvQOxfAu/7pnTwQx4ty63A2Wy7WngRW7DsEni2U9y6EVYa+77JKDuQKd/KSiGwH0NwMMuEjzXjrFdI6m+NWcyAOUDum0AyvCNRHWk1TGzNwBs/7llH4aPFZHJjjHdJqo8RX12M69wgj+xJdIl7j3XFFeAtKKAmM40oJiFkMO8OGOQvQUB3eV0x+cPY1u+XL5lO8PolILTzqqQ7lDJnvnLsd/MoZw3NUt2zHspRvW1ceX4FRTKU/ZI+QJrRX/65l/el+MQl9Nt4/epoSF/5nuYgEZfRb2h0hm+Iva2RCwIJhcXSRZ+/B0hauT34Uwr1YTCSWO/4VR2qaiuZvQMtgkhAU6uP0sdl8kyZVwAhNqXbDWewFQXXkGSzPCiqfcZdmRY6s5PSJ0qhzGl8BMDMPYy6EqFCLigLxgn+dKV/C/iRx7SqoZRvZN5uGFcCeu4MYGaEZVSPA/TXfOOtv0qoA/ewxNHJroL2ja98mmsWxR4qKniHTl7VM6gKFmkjGqvW+Zc6jWY3/EywrSUWuwvZrJ/pM=
  cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: xinp-hub/pydiggs
    python: 3.8
env:
  global:
    secure: EkO7/LmXi/1c6H1G2XMUhdGzAsbg0Z5jO+R7cwk8ZH691iKhDWPsFIORplI/2M/4sXG9CzX3GIxfMz5XTY42t7Brfj2VN8Q2g6N3tOahLXniBdr+bCbJCsBFFu22KJm7EeP3aLwiaJa5xfcz/MOBA401lLh/ytdMtj2UbhLPVaZkculT48AfcJjof5N55H4+GtKRwZW2mG5uA/LX0V14BspuzAT9x4jcOHckeePpHzCF6ahJHSJBp2IRxuL/fZmfMrmVGVttmjzxVIlPaKB6rHMYmC46sIEIIrYAjnYuifsQeAqu3wnQQVcfB6H/m8ROq7U+DsWT5/6fX7cCU90VzGU3hs4Ry1gMZWFKX/zfnsmVxN6wafCtsG+J8jcBJyNMT56KZUqBDWegpqiGlCc5QKcBqgs6Jarq7e17Hw1neYT3svOjq/sIRe1/LNwDunMIQ8QHtlRPIPH3YP6iiG1Cec5gdMFw/eaRuy04it2UtRDPEulV9+mPfw9HUw4dZte7wgCQxdXcGvjyPhz+sW644PX2i5Jw6OHEroUVvYvZffpUW9u9sFvFM1cbLQ6og+g7u17SCJO1fksC92gIrOgO8CnwvjoByLLoGTVaUn+lMtSVRxH9II52k6kS65MzQeEst4Ll30AP6GPPTrQqTzByX+rGzr9zAaS5hVml8IMHBe8=
