language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: 0GD9azuIeoNz8y0la4YsCdI/L7QX/Ku/cNbpUvIMHXn0x6fEmn8XJ6neCVlA8BBrFPg38qGSenBECKjNLpn4Efzqupalfhkpn/AhhQ0O/ZzfZ0KjYfBrzJO5ib7CxhSU34Pd4DJem8iG//axWcPbu+crm/zfulzBi+WPlrqnX4mIWI7edZj/8BwZQI4KXXUBxmiZK6+dukbUNucmG/XmtzUBfUOwmCgiCSEFr5hjQsG0XWOb2vS4rSU6XfkwPQOaAhqrQcswuCM4wrsT4Il9S6FGhZEBYuk2jNsSeJc5AGZX22HzF8RbhhE2Ahocr5ouiAWJkaPpobWZVKVQW39745eiHG8GuxawxKU3c1kZlWx9Mr7lJiX7laNFfqiAM8fU6X4iH/fCMQqXdRFJkH8qro0/0pEFIF9tidGYyz9TX1cPk9X9Gi0/nw3VYvgSJcfEK6fxwriikDUNN4xnp+YbkcCvPcGM9hbaHy6rl3j8oIaLI4h0d0bYpnLXmiaRmo0la0av7zJnMRSkajj4OzKU49WYipk86O5PUb4Djl1kFBX4vleu6O9zH+Vo1RWrRAWc5gfWncMz2sxhzttsJfcuULkXr2ndJ6hC4bbyGxn5k7T6iNjXghpD0V0HX2j9oRqnVPYKDa2FKfSSGNQWZembwSWOzLSPNquyM28zF6FaZ90=
  cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: xinp-hub/pydiggs
    python: 3.8
env:
  global:
    secure: EkO7/LmXi/1c6H1G2XMUhdGzAsbg0Z5jO+R7cwk8ZH691iKhDWPsFIORplI/2M/4sXG9CzX3GIxfMz5XTY42t7Brfj2VN8Q2g6N3tOahLXniBdr+bCbJCsBFFu22KJm7EeP3aLwiaJa5xfcz/MOBA401lLh/ytdMtj2UbhLPVaZkculT48AfcJjof5N55H4+GtKRwZW2mG5uA/LX0V14BspuzAT9x4jcOHckeePpHzCF6ahJHSJBp2IRxuL/fZmfMrmVGVttmjzxVIlPaKB6rHMYmC46sIEIIrYAjnYuifsQeAqu3wnQQVcfB6H/m8ROq7U+DsWT5/6fX7cCU90VzGU3hs4Ry1gMZWFKX/zfnsmVxN6wafCtsG+J8jcBJyNMT56KZUqBDWegpqiGlCc5QKcBqgs6Jarq7e17Hw1neYT3svOjq/sIRe1/LNwDunMIQ8QHtlRPIPH3YP6iiG1Cec5gdMFw/eaRuy04it2UtRDPEulV9+mPfw9HUw4dZte7wgCQxdXcGvjyPhz+sW644PX2i5Jw6OHEroUVvYvZffpUW9u9sFvFM1cbLQ6og+g7u17SCJO1fksC92gIrOgO8CnwvjoByLLoGTVaUn+lMtSVRxH9II52k6kS65MzQeEst4Ll30AP6GPPTrQqTzByX+rGzr9zAaS5hVml8IMHBe8=
